// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateListingsSystem.Data;

#nullable disable

namespace RealEstateListingsSystem.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    [Migration("20260214143703_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateListingsSystem.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivan.petrov@realestate.bg",
                            FullName = "Ivan Petrov",
                            PhoneNumber = "0888123456"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.georgieva@realestate.bg",
                            FullName = "Maria Georgieva",
                            PhoneNumber = "0899123456"
                        });
                });

            modelBuilder.Entity("RealEstateListingsSystem.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "15 Vitosha Blvd, Sofia",
                            AgentId = 1,
                            Description = "A beautiful modern apartment located in the city center with excellent infrastructure nearby.",
                            Price = 125000m,
                            PropertyTypeId = 1,
                            Size = 85,
                            Title = "Modern Two-Bedroom Apartment"
                        },
                        new
                        {
                            Id = 2,
                            Address = "22 Rose Street, Plovdiv",
                            AgentId = 2,
                            Description = "Spacious family house with private garden and garage, located in a quiet residential area.",
                            Price = 350000m,
                            PropertyTypeId = 2,
                            Size = 240,
                            Title = "Luxury Family House with Garden"
                        },
                        new
                        {
                            Id = 3,
                            Address = "8 Studentski Grad, Sofia",
                            AgentId = 1,
                            Description = "Compact and practical studio apartment suitable for students or investment purposes.",
                            Price = 75000m,
                            PropertyTypeId = 1,
                            Size = 40,
                            Title = "Cozy Studio Near University"
                        });
                });

            modelBuilder.Entity("RealEstateListingsSystem.Models.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apartment"
                        },
                        new
                        {
                            Id = 2,
                            Name = "House"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Studio"
                        });
                });

            modelBuilder.Entity("RealEstateListingsSystem.Models.Property", b =>
                {
                    b.HasOne("RealEstateListingsSystem.Models.Agent", "Agent")
                        .WithMany("Properties")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateListingsSystem.Models.PropertyType", "PropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("RealEstateListingsSystem.Models.Agent", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RealEstateListingsSystem.Models.PropertyType", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
